// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_HEARTBEAT   EventType = 1
	EventType_EVENT_TYPE_MESSAGE     EventType = 2
	EventType_EVENT_TYPE_DONG        EventType = 3
	EventType_EVENT_TYPE_ERROR       EventType = 16
	EventType_EVENT_TYPE_FRIENDSHIP  EventType = 17
	EventType_EVENT_TYPE_ROOM_INVITE EventType = 18
	EventType_EVENT_TYPE_ROOM_JOIN   EventType = 19
	EventType_EVENT_TYPE_ROOM_LEAVE  EventType = 20
	EventType_EVENT_TYPE_ROOM_TOPIC  EventType = 21
	EventType_EVENT_TYPE_SCAN        EventType = 22
	EventType_EVENT_TYPE_READY       EventType = 23
	EventType_EVENT_TYPE_RESET       EventType = 24
	EventType_EVENT_TYPE_LOGIN       EventType = 25
	EventType_EVENT_TYPE_LOGOUT      EventType = 26
)

var EventType_name = map[int32]string{
	0:  "EVENT_TYPE_UNSPECIFIED",
	1:  "EVENT_TYPE_HEARTBEAT",
	2:  "EVENT_TYPE_MESSAGE",
	3:  "EVENT_TYPE_DONG",
	16: "EVENT_TYPE_ERROR",
	17: "EVENT_TYPE_FRIENDSHIP",
	18: "EVENT_TYPE_ROOM_INVITE",
	19: "EVENT_TYPE_ROOM_JOIN",
	20: "EVENT_TYPE_ROOM_LEAVE",
	21: "EVENT_TYPE_ROOM_TOPIC",
	22: "EVENT_TYPE_SCAN",
	23: "EVENT_TYPE_READY",
	24: "EVENT_TYPE_RESET",
	25: "EVENT_TYPE_LOGIN",
	26: "EVENT_TYPE_LOGOUT",
}

var EventType_value = map[string]int32{
	"EVENT_TYPE_UNSPECIFIED": 0,
	"EVENT_TYPE_HEARTBEAT":   1,
	"EVENT_TYPE_MESSAGE":     2,
	"EVENT_TYPE_DONG":        3,
	"EVENT_TYPE_ERROR":       16,
	"EVENT_TYPE_FRIENDSHIP":  17,
	"EVENT_TYPE_ROOM_INVITE": 18,
	"EVENT_TYPE_ROOM_JOIN":   19,
	"EVENT_TYPE_ROOM_LEAVE":  20,
	"EVENT_TYPE_ROOM_TOPIC":  21,
	"EVENT_TYPE_SCAN":        22,
	"EVENT_TYPE_READY":       23,
	"EVENT_TYPE_RESET":       24,
	"EVENT_TYPE_LOGIN":       25,
	"EVENT_TYPE_LOGOUT":      26,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

type EventRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

type EventResponse struct {
	Type EventType `protobuf:"varint,1,opt,name=type,proto3,enum=wechaty.puppet.EventType" json:"type,omitempty"`
	// TODO: Huan(202002) consider to use a PB Map?
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (m *EventResponse) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterEnum("wechaty.puppet.EventType", EventType_name, EventType_value)
	proto.RegisterType((*EventRequest)(nil), "wechaty.puppet.EventRequest")
	proto.RegisterType((*EventResponse)(nil), "wechaty.puppet.EventResponse")
}

func init() {
	proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e)
}

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdd, 0xae, 0xd2, 0x40,
	0x14, 0x85, 0x2d, 0x12, 0x95, 0x51, 0x61, 0x33, 0xfc, 0x58, 0xb8, 0x22, 0x5c, 0x11, 0x12, 0xdb,
	0x44, 0x9f, 0xa0, 0xd0, 0x0d, 0x8c, 0x81, 0x99, 0x66, 0x3a, 0x10, 0xf1, 0x86, 0x00, 0x4e, 0x80,
	0x44, 0xe9, 0x08, 0x45, 0xd3, 0xa7, 0xd7, 0x50, 0x39, 0x27, 0xa5, 0xe7, 0x5c, 0xee, 0xef, 0x5b,
	0x6d, 0x56, 0xb2, 0x86, 0xbc, 0xd5, 0xbf, 0xf5, 0x31, 0x76, 0xcc, 0x29, 0x8a, 0x23, 0x5a, 0xfe,
	0xa3, 0xb7, 0xfb, 0x75, 0x9c, 0x38, 0xe6, 0x62, 0x8c, 0x8e, 0xbb, 0x65, 0xf2, 0x0e, 0xaf, 0x5a,
	0xea, 0x5f, 0x17, 0x7d, 0x8e, 0xbb, 0x5f, 0xc9, 0xfb, 0xdb, 0x7d, 0x36, 0xd1, 0xf1, 0xac, 0xe9,
	0x47, 0x52, 0x8c, 0x13, 0xa3, 0x6d, 0xab, 0x63, 0xf5, 0xca, 0x9f, 0x5a, 0xce, 0xfd, 0xf7, 0x4e,
	0x1a, 0x56, 0x89, 0xd1, 0x32, 0x8d, 0x51, 0x9b, 0xbc, 0x36, 0xeb, 0xe4, 0x47, 0xb4, 0xfe, 0x6e,
	0x17, 0x3a, 0x56, 0xaf, 0x24, 0x1f, 0xce, 0xfe, 0xdf, 0x02, 0x29, 0x3d, 0xa6, 0x69, 0x9b, 0x34,
	0x71, 0x81, 0x5c, 0xad, 0xd4, 0x32, 0xc0, 0xd5, 0x9c, 0x87, 0x01, 0x0e, 0xd9, 0x88, 0xa1, 0x0f,
	0x2f, 0xa8, 0x4d, 0xea, 0x19, 0x37, 0x41, 0x4f, 0xaa, 0x01, 0x7a, 0x0a, 0x2c, 0xda, 0x24, 0x34,
	0x63, 0x66, 0x18, 0x86, 0xde, 0x18, 0xa1, 0x40, 0x6b, 0xa4, 0x92, 0xe1, 0xbe, 0xe0, 0x63, 0x78,
	0x49, 0xeb, 0x04, 0x32, 0x10, 0xa5, 0x14, 0x12, 0x80, 0xb6, 0x48, 0x23, 0x43, 0x47, 0x92, 0x21,
	0xf7, 0xc3, 0x09, 0x0b, 0xa0, 0x9a, 0xeb, 0x24, 0x85, 0x98, 0xad, 0x18, 0x5f, 0x30, 0x85, 0x40,
	0x73, 0x9d, 0x52, 0xf7, 0x45, 0x30, 0x0e, 0xb5, 0xdc, 0x0f, 0x53, 0x33, 0x45, 0x6f, 0x81, 0x50,
	0x7f, 0x4e, 0x29, 0x11, 0xb0, 0x21, 0x34, 0x72, 0x8d, 0xc3, 0xa1, 0xc7, 0xa1, 0x99, 0x6b, 0x2c,
	0xd1, 0xf3, 0x97, 0xf0, 0xe1, 0x09, 0x0d, 0x51, 0x81, 0x9d, 0xa3, 0x53, 0x31, 0x66, 0x1c, 0x5a,
	0xb4, 0x41, 0xaa, 0xf7, 0x54, 0xcc, 0x15, 0xb4, 0xbb, 0xc5, 0x37, 0x45, 0xa8, 0x0c, 0xfa, 0xdf,
	0x7a, 0xbb, 0x43, 0xbc, 0xbf, 0x6c, 0x9c, 0x6d, 0xf4, 0xd3, 0xbd, 0xce, 0x78, 0xd0, 0xee, 0xee,
	0x64, 0xb6, 0xee, 0x2e, 0x72, 0x6f, 0xbb, 0xba, 0xff, 0x77, 0xdd, 0xbc, 0x4a, 0x9f, 0xcb, 0xe7,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x0c, 0x58, 0xa5, 0x3d, 0x02, 0x00, 0x00,
}
