// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package puppet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TagContactAddRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactAddRequest) Reset()         { *m = TagContactAddRequest{} }
func (m *TagContactAddRequest) String() string { return proto.CompactTextString(m) }
func (*TagContactAddRequest) ProtoMessage()    {}
func (*TagContactAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{0}
}

func (m *TagContactAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactAddRequest.Unmarshal(m, b)
}
func (m *TagContactAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactAddRequest.Marshal(b, m, deterministic)
}
func (m *TagContactAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactAddRequest.Merge(m, src)
}
func (m *TagContactAddRequest) XXX_Size() int {
	return xxx_messageInfo_TagContactAddRequest.Size(m)
}
func (m *TagContactAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactAddRequest proto.InternalMessageInfo

func (m *TagContactAddRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TagContactAddRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type TagContactAddResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactAddResponse) Reset()         { *m = TagContactAddResponse{} }
func (m *TagContactAddResponse) String() string { return proto.CompactTextString(m) }
func (*TagContactAddResponse) ProtoMessage()    {}
func (*TagContactAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{1}
}

func (m *TagContactAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactAddResponse.Unmarshal(m, b)
}
func (m *TagContactAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactAddResponse.Marshal(b, m, deterministic)
}
func (m *TagContactAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactAddResponse.Merge(m, src)
}
func (m *TagContactAddResponse) XXX_Size() int {
	return xxx_messageInfo_TagContactAddResponse.Size(m)
}
func (m *TagContactAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactAddResponse proto.InternalMessageInfo

type TagContactRemoveRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactRemoveRequest) Reset()         { *m = TagContactRemoveRequest{} }
func (m *TagContactRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*TagContactRemoveRequest) ProtoMessage()    {}
func (*TagContactRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{2}
}

func (m *TagContactRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactRemoveRequest.Unmarshal(m, b)
}
func (m *TagContactRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactRemoveRequest.Marshal(b, m, deterministic)
}
func (m *TagContactRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactRemoveRequest.Merge(m, src)
}
func (m *TagContactRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_TagContactRemoveRequest.Size(m)
}
func (m *TagContactRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactRemoveRequest proto.InternalMessageInfo

func (m *TagContactRemoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TagContactRemoveRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type TagContactRemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactRemoveResponse) Reset()         { *m = TagContactRemoveResponse{} }
func (m *TagContactRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*TagContactRemoveResponse) ProtoMessage()    {}
func (*TagContactRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{3}
}

func (m *TagContactRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactRemoveResponse.Unmarshal(m, b)
}
func (m *TagContactRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactRemoveResponse.Marshal(b, m, deterministic)
}
func (m *TagContactRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactRemoveResponse.Merge(m, src)
}
func (m *TagContactRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_TagContactRemoveResponse.Size(m)
}
func (m *TagContactRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactRemoveResponse proto.InternalMessageInfo

type TagContactDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactDeleteRequest) Reset()         { *m = TagContactDeleteRequest{} }
func (m *TagContactDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TagContactDeleteRequest) ProtoMessage()    {}
func (*TagContactDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{4}
}

func (m *TagContactDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactDeleteRequest.Unmarshal(m, b)
}
func (m *TagContactDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactDeleteRequest.Marshal(b, m, deterministic)
}
func (m *TagContactDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactDeleteRequest.Merge(m, src)
}
func (m *TagContactDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TagContactDeleteRequest.Size(m)
}
func (m *TagContactDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactDeleteRequest proto.InternalMessageInfo

func (m *TagContactDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TagContactDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactDeleteResponse) Reset()         { *m = TagContactDeleteResponse{} }
func (m *TagContactDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*TagContactDeleteResponse) ProtoMessage()    {}
func (*TagContactDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{5}
}

func (m *TagContactDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactDeleteResponse.Unmarshal(m, b)
}
func (m *TagContactDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactDeleteResponse.Marshal(b, m, deterministic)
}
func (m *TagContactDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactDeleteResponse.Merge(m, src)
}
func (m *TagContactDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_TagContactDeleteResponse.Size(m)
}
func (m *TagContactDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactDeleteResponse proto.InternalMessageInfo

type TagContactListRequest struct {
	ContactId            *wrappers.StringValue `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TagContactListRequest) Reset()         { *m = TagContactListRequest{} }
func (m *TagContactListRequest) String() string { return proto.CompactTextString(m) }
func (*TagContactListRequest) ProtoMessage()    {}
func (*TagContactListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{6}
}

func (m *TagContactListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactListRequest.Unmarshal(m, b)
}
func (m *TagContactListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactListRequest.Marshal(b, m, deterministic)
}
func (m *TagContactListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactListRequest.Merge(m, src)
}
func (m *TagContactListRequest) XXX_Size() int {
	return xxx_messageInfo_TagContactListRequest.Size(m)
}
func (m *TagContactListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactListRequest proto.InternalMessageInfo

func (m *TagContactListRequest) GetContactId() *wrappers.StringValue {
	if m != nil {
		return m.ContactId
	}
	return nil
}

type TagContactListResponse struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagContactListResponse) Reset()         { *m = TagContactListResponse{} }
func (m *TagContactListResponse) String() string { return proto.CompactTextString(m) }
func (*TagContactListResponse) ProtoMessage()    {}
func (*TagContactListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{7}
}

func (m *TagContactListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagContactListResponse.Unmarshal(m, b)
}
func (m *TagContactListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagContactListResponse.Marshal(b, m, deterministic)
}
func (m *TagContactListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagContactListResponse.Merge(m, src)
}
func (m *TagContactListResponse) XXX_Size() int {
	return xxx_messageInfo_TagContactListResponse.Size(m)
}
func (m *TagContactListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TagContactListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TagContactListResponse proto.InternalMessageInfo

func (m *TagContactListResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*TagContactAddRequest)(nil), "wechaty.puppet.TagContactAddRequest")
	proto.RegisterType((*TagContactAddResponse)(nil), "wechaty.puppet.TagContactAddResponse")
	proto.RegisterType((*TagContactRemoveRequest)(nil), "wechaty.puppet.TagContactRemoveRequest")
	proto.RegisterType((*TagContactRemoveResponse)(nil), "wechaty.puppet.TagContactRemoveResponse")
	proto.RegisterType((*TagContactDeleteRequest)(nil), "wechaty.puppet.TagContactDeleteRequest")
	proto.RegisterType((*TagContactDeleteResponse)(nil), "wechaty.puppet.TagContactDeleteResponse")
	proto.RegisterType((*TagContactListRequest)(nil), "wechaty.puppet.TagContactListRequest")
	proto.RegisterType((*TagContactListResponse)(nil), "wechaty.puppet.TagContactListResponse")
}

func init() {
	proto.RegisterFile("tag.proto", fileDescriptor_27f545bcde37ecb5)
}

var fileDescriptor_27f545bcde37ecb5 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xcb, 0x4b, 0xc3, 0x40,
	0x10, 0x87, 0x69, 0x0a, 0x42, 0x46, 0x28, 0x12, 0xd4, 0x86, 0xa2, 0x52, 0x72, 0x8a, 0x3d, 0xec,
	0x82, 0x1e, 0x3d, 0xf9, 0x02, 0x05, 0x4f, 0xb1, 0x78, 0xf0, 0x22, 0x9b, 0xec, 0xb8, 0x5d, 0x48,
	0xb3, 0x6b, 0x76, 0x62, 0xf1, 0xbf, 0x97, 0xbc, 0x30, 0xad, 0x78, 0xf1, 0xb6, 0xcc, 0x0c, 0xdf,
	0x37, 0x3b, 0x3f, 0xf0, 0x49, 0x28, 0x66, 0x4b, 0x43, 0x26, 0x98, 0x6c, 0x30, 0x5b, 0x09, 0xfa,
	0x62, 0xb6, 0xb2, 0x16, 0x69, 0x76, 0xa6, 0x8c, 0x51, 0x39, 0xf2, 0xa6, 0x9b, 0x56, 0xef, 0x7c,
	0x53, 0x0a, 0x6b, 0xb1, 0x74, 0xed, 0x7c, 0x74, 0x0f, 0x87, 0x4b, 0xa1, 0x6e, 0x4d, 0x41, 0x22,
	0xa3, 0x6b, 0x29, 0x13, 0xfc, 0xa8, 0xd0, 0x51, 0x30, 0x01, 0x4f, 0xcb, 0x70, 0x34, 0x1f, 0xc5,
	0x7e, 0xe2, 0x69, 0x19, 0x9c, 0x02, 0x64, 0xed, 0xd0, 0x9b, 0x96, 0xa1, 0xd7, 0xd4, 0xfd, 0xae,
	0xf2, 0x28, 0xa3, 0x29, 0x1c, 0xed, 0x60, 0x9c, 0x35, 0x85, 0xc3, 0xe8, 0x01, 0xa6, 0x3f, 0x8d,
	0x04, 0xd7, 0xe6, 0x13, 0xff, 0xa9, 0x98, 0x41, 0xf8, 0x9b, 0xd4, 0x59, 0xce, 0x87, 0x96, 0x3b,
	0xcc, 0x91, 0xfe, 0xb2, 0x6c, 0x63, 0xfa, 0xd1, 0x0e, 0xb3, 0x1c, 0xfe, 0xe2, 0x49, 0x3b, 0xea,
	0x21, 0x57, 0x5b, 0xab, 0xd5, 0xb0, 0xfd, 0x8b, 0x13, 0xd6, 0x9e, 0x96, 0xf5, 0xa7, 0x65, 0xcf,
	0x54, 0xea, 0x42, 0xbd, 0x88, 0xbc, 0xc2, 0xe1, 0xe2, 0x0b, 0x38, 0xde, 0xa5, 0xb6, 0xbe, 0xe0,
	0x00, 0xc6, 0x5a, 0xba, 0x70, 0x34, 0x1f, 0xc7, 0x7e, 0x52, 0x3f, 0x6f, 0x16, 0xaf, 0xb1, 0xd2,
	0xb4, 0xaa, 0x52, 0x96, 0x99, 0x35, 0xaf, 0x93, 0xd4, 0xc8, 0x55, 0x69, 0x33, 0xae, 0x0c, 0xef,
	0xa2, 0xe5, 0x6d, 0xb4, 0xe9, 0x5e, 0x23, 0xbe, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x7c,
	0x7e, 0x7a, 0xfe, 0x01, 0x00, 0x00,
}
