export * from '../generated/wechaty/puppet/base_pb'
export * from '../generated/wechaty/puppet/contact_pb'
export * from '../generated/wechaty/puppet/event_pb'
export * from '../generated/wechaty/puppet/friendship_pb'
export * from '../generated/wechaty/puppet/message_pb'
export * from '../generated/wechaty/puppet/room_invitation_pb'
export * from '../generated/wechaty/puppet/room_member_pb'
export * from '../generated/wechaty/puppet/room_pb'
export * from '../generated/wechaty/puppet/tag_pb'

export * from '../generated/wechaty/puppet_grpc_pb'
export * from '../generated/wechaty/puppet_pb'
