export * from '../generated/wechaty/puppet/base_pb.js'
export * from '../generated/wechaty/puppet/contact_pb.js'
export * from '../generated/wechaty/puppet/event_pb.js'
export * from '../generated/wechaty/puppet/file_box_pb.js'
export * from '../generated/wechaty/puppet/friendship_pb.js'
export * from '../generated/wechaty/puppet/message_pb.js'
export * from '../generated/wechaty/puppet/room_invitation_pb.js'
export * from '../generated/wechaty/puppet/room_member_pb.js'
export * from '../generated/wechaty/puppet/room_pb.js'
export * from '../generated/wechaty/puppet/tag_pb.js'

export * from '../generated/wechaty/puppet_grpc_pb.js'
export * from '../generated/wechaty/puppet_pb.js'
