name: "csharp"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: push package
      run: .\publish.ps1
      working-directory: .\csharp\Wechaty.Grpc\buildTool
      shell: powershell
      with:
        args: 123456789
