name: C# Nuget
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: copy wechaty proto
      run: .\copy.ps1
      working-directory: .\polyglot\csharp\Wechaty.Grpc\buildTool
      shell: powershell

    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: .\polyglot\csharp\Wechaty.Grpc\Wechaty.Grpc.csproj
        VERSION_FILE_PATH: .\polyglot\csharp\Wechaty.Grpc\common.props
        NUGET_KEY: ${{ secrets.NUGET_APIKEY }}
