name: "csharp"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-push:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: push package
      run: .\publish.ps1 ${{ secrets.NUGET_APIKEY }}
      working-directory: .\csharp\Wechaty.Grpc\buildTool
      shell: powershell
