name: C# Nuget

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'polyglot/csharp/**'
      - 'proto/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.1.100

    - name: copy wechaty proto
      run: .\copy.ps1
      working-directory: .\polyglot\csharp\Wechaty.Grpc\buildTool
      shell: powershell
